name: Deploy to Test Repository

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'test-vasvag-changes'
        
jobs:
  deploy-to-test-repo:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build documentation
      run: |
        sphinx-build -b html . _build
        
    - name: Deploy to separate test repository
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # You'll need to create this
        external_repository: biosustain/data-catalog-resources-test  # Create this repo
        publish_dir: ./_build
        commit_message: 'Test deployment from ${{ github.event.inputs.branch }}: ${{ github.sha }}'
